<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ApprovalEntry extends Model
{
    protected $guarded = [];
    protected $table = "approval_entries";
    protected $primaryKey = "id";
    public $incrementing = true;
    public $timestamps = true;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updated(function ($employee){
            Event::fire('approval_entry.updated', $employee);
        });
    }
}
